name: sotsuken2
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0
  image_picker: ^1.0.5
  image_cropper:  ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/img.png"
